config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  resources :appointments do
    resources :exams, except: [:index] do
      member do
        delete :delete_exam_attached
      end
    end
    resources :treatments, except: [:index]
  end

  get 'home', to: 'home#index'

  get '/dashboard', to: 'dashboard#index'
  get '/shared_history', to: 'shared_users#index'
  post '/search_shared_user', to: 'shared_users#search_user'

  resources :shared_users, only: %i[destroy create]

  devise_for :users
  get '/user' => 'dashboard#index', as: :user_root

  ## Essas linha de codigo tem que esta por ultimo.
  get 'fatal_test', to: 'errors#fatal_test'
  get 'error_test', to: 'errors#error_test'

  match '*path', to: 'errors#not_found', via: :all
  ##
end

app/models/treatment.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: treatments
#
#  id                 :bigint           not null, primary key
#  title              :string           not null
#  description        :text             not null
#  establishment_name :string           not null
#  kind               :integer          not null
#  treatment_date     :date             not null
#  appointment_id     :bigint           not null
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#
class Treatment < ApplicationRecord
  # Active Record Associations
  belongs_to :appointment
  has_one :user, through: :appointment

  # Active Record Validations
  validates :title, :description, :establishment_name, :kind, :treatment_date, presence: true

  enum kind: {
    medicine: 0,
    physiotherapy: 1
  }
end

app/controllers/treatments_controller.rb
# frozen_string_literal: true

class TreatmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_appointment
  before_action :set_treatment, only: %i[show edit update destroy]
  layout 'dashboard'
  # GET /treatments
  # GET /treatments.json
  def index
    @treatments = @appointment.treatments
  end

  # GET /treatments/1
  # GET /treatments/1.json
  def show; end

  # GET /treatments/new
  def new
    @treatment = @appointment.treatments.build
  end

  # GET /treatments/1/edit
  def edit; end

  # POST /treatments
  # POST /treatments.json
  def create
    @treatment = @appointment.treatments.build(treatment_params)

    respond_to do |format|
      if @treatment.save
        format.html do
          # Ao criar um novo tratamento você voltará para a tela de consulta
          redirect_to appointment_path(@appointment), notice: 'Tratamento adicionado com sucesso.'
        end
        format.json { render :show, status: :created, location: @treatment }
      else
        format.html { render :new }
        format.json { render json: @treatment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /treatments/1
  # PATCH/PUT /treatments/1.json
  def update
    respond_to do |format|
      if @treatment.update(treatment_params)
        format.html do
          # Ao realizar o atualização você voltará ao tela do tratamento atualizado
          redirect_to appointment_treatment_path(@appointment), notice: 'Tratamento atualizado com sucesso.'
        end
        format.json { render :show, status: :ok, location: @treatment }
      else
        format.html { render :edit }
        format.json { render json: @treatment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /treatments/1
  # DELETE /treatments/1.json
  def destroy
    @treatment.destroy
    respond_to do |format|
      format.html do
        # Ao remover o tratamento você voltará ao show da consulta
        redirect_to appointment_path(@appointment), notice: 'Tratamento removido com sucesso.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_treatment
    @treatment = @appointment.treatments.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def treatment_params
    params.require(:treatment).permit(:title, :description, :establishment_name, :kind, :treatment_date,
                                      :appointment_id)
  end

  def get_appointment
    @appointment = Appointment.find(params[:appointment_id])
  end
end

app/helpers/treatments_helper.rb
# frozen_string_literal: true

module TreatmentsHelper
end

app/views/treatments/_form.html.erb
<!--
  O mesmo para adicionar um tratamento e atualizar um tratamento
  Mostrar o título do tratamento 
  Mostrar a descrição do tratamento
  Mostrar o nome do estabelecimento onde foi feito o tratamento 
  Mostrar do Tratamento enum > Campo enum > TODO: pode ser adicionado mais
  Mostrar a data do tratamento
  Tem o botão para criar o tratamento ou salvar
-->
<div class="container">
  <div class="d-flex justify-content-center col-sm-12 col-md-10 col-lg">
    <div class="col-lg-10">
			<%= simple_form_for([@appointment, @treatment]) do |f| %>
				<%= f.error_notification %>
				<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  			<div class="form-group">
  				<%= f.input :title, label: 'Título' %>
  				<%= f.input :description, label: 'Descrição' %>
  				<%= f.input :establishment_name, label: 'Nome do Estabelecimento' %>
  				<!-- <%= f.input :kind %> -->
  				<%= f.input :kind, collection: Treatment.kinds.keys %>
  				<%= f.datetime_field :treatment_date %>
  				<!-- <%= f.association :appointment %> -->

          <% if action_name == 'edit'%>  
            <%= f.button :submit, "Editar Tratamento" , {class:"btn mt-3 button-submit-auth-entry mb-4 btn-lg btn-block text-center"} %>
          <% else %>
            <%= f.button :submit, "Criar Tratamento" , {class:"btn mt-3 button-submit-auth-entry mb-4 btn-lg btn-block text-center"} %>
          <% end %>
        </div>
			<% end %>
		</div>
	</div>
</div>

app/views/treatments/edit.html.erb
<div class="container-fluid show_card tables_standart">
  <div class="cards">
    <div class="card">
    	<div class="contents ">
				<div class="container-sm interactive_button">
					<h1 class="text-center">Editar Tratamento</h1>
					<%= render 'form', treatment: @treatment %>
					<%= link_to 'Voltar', appointment_path(@appointment), class:"btn-info button_style_horizontal btn mb-4 text-left" %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/treatments/index.html.erb
<p id="notice">
  <%= notice %>
</p>
<div class="tables_standart mb-5">
  <h1>Tratamentos</h1>

  <table class="table table-hover" data-toggle="table" data-search="true" data-strict-search="true">
    <thead>
      <tr>
        <th>Titulo</th>
        <th>Data</th>
        <th>Local do Tratamento</th>
        <th colspan="2" style="background-color: var(--color-primary)"></th>
      </tr>
    </thead>

    <tbody>
      <% @treatments.each do |treatment| %>
        <tr>
          <td>
            <%= treatment.title %>
          </td>
          <td>
            <%= treatment.treatment_date.strftime('%d/%m') %>
          </td>
          <td>
            <%= treatment.establishment_name %>
          </td>
          <% unless @shared_user%>
            <td>
              <%= link_to edit_appointment_treatment_path(@appointment, treatment) do %>
                <%= image_tag 'icon_edit.svg' %>
                  <% end %>
            </td>
            <td>
              <%= link_to [@appointment, treatment], method: :delete, data: { confirm: 'Você tem certeza?' } do %>
                <%= image_tag('icon_trash.svg')%>
                  <% end %>
            </td>
            <% end %>
        </tr>
        <% end %>
    </tbody>

  </table>
</div>

app/views/treatments/new.html.erb
<div class="container-fluid show_card tables_standart">
  <div class="cards">
    <div class="card">
    	<div class="contents ">
				<div class="container-sm interactive_button">
					<h1 class="text-center">Novo Tratamento</h1>
					<%= render 'form', treatment: @treatment %>
					<%= link_to 'Voltar', appointment_path(@appointment), class:"btn-info button_style_horizontal btn mb-4 text-left" %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/treatments/show.html.erb
<!--
  Detalhes do Tratamento 
  Tabela com detalhes rápidos sobre o tratamento Título Data Local do Tratamento
  Botão para editar o tratamento 
  Botão para deletar o exame
  Extra => botão de voltar 
-->
<p id="notice">
  <%= notice %>
</p>
<div class="container-fluid show_card">
  <div class="cards">
    <div class="card">
      <input type="checkbox" id="bgtoggle" class="toggle" />
      <label for="bgtoggle" class="menu"></label>

      <!-- Data the appointments -->

      <div class="contents">
        <div class="container-fluid">
          <div class="row mb-3">
            <h5 class="attribute_camp mr-4">Título :</h5> <span class="attribute_value">
              <%= @treatment.title %>
            </span>
          </div>

          <div class="row mb-3">
            <h5 class="attribute_camp mr-4">Data de Tratamento :</h5> <span class="attribute_value">
              <%= @treatment.treatment_date.strftime('%d/%m/%y') %>
            </span>
          </div>

          <div class="row mb-3">
            <h5 class="attribute_camp mr-4">Local de Tratamento :</h5> <span class="attribute_value">
              <%= @treatment.establishment_name %>
            </span>
          </div>

          <% unless @shared_user %>
            <div class="row mt-5 interactive_button">

              <%= link_to 'Editar' , edit_appointment_treatment_path(@appointment, @treatment),
                class:"button_style_horizontal btn mb-4 btn-sm btn-block text-left" %>

                <%= link_to 'Remover Tratamento' , [@appointment, @treatment], method: :delete, data: {
                  confirm: 'Você tem certeza?' }, class:"button_style_horizontal btn mb-4 btn-sm btn-block text-left" %>

                  <%= link_to 'Voltar à Consulta' , appointment_path(@appointment), class:"btn-info
                    button_style_horizontal btn mb-4 btn-sm btn-block text-left" %>
            </div>
            <% end%>
        </div>
      </div>
    </div>
  </div>
</div>