config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  resources :appointments do
    resources :exams, except: [:index] do
      member do
        delete :delete_exam_attached
      end
    end
    resources :treatments, except: [:index]
  end

  get 'home', to: 'home#index'

  get '/dashboard', to: 'dashboard#index'
  get '/shared_history', to: 'shared_users#index'
  post '/search_shared_user', to: 'shared_users#search_user'

  resources :shared_users, only: %i[destroy create]

  devise_for :users
  get '/user' => 'dashboard#index', as: :user_root

  ## Essas linha de codigo tem que esta por ultimo.
  get 'fatal_test', to: 'errors#fatal_test'
  get 'error_test', to: 'errors#error_test'

  match '*path', to: 'errors#not_found', via: :all
  ##
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  before_action :authenticate_user!
  layout 'dashboard'

  def index
    if params[:search].present?
      sql = "SELECT
							a.title as title,
							a.appointment_date as date,
							a.professional_name as professional,
							'-' as establishment,
							'appointments/' || a.id as link
						FROM
							appointments a
						WHERE
							a.user_id = #{current_user.id} AND
							a.title ILIKE '%#{params[:search]}%'
						UNION
						SELECT
							e.title as title,
							e.exam_date as date,
							'-' as professional,
							e.establishment_name as establishment,
							'appointments/' || e.appointment_id || '/exams/' || e.id as link
						FROM
							exams e
						WHERE
							e.title ILIKE '%#{params[:search]}%' AND
							e.appointment_id IN (SELECT id
								FROM appointments
								WHERE user_id = #{current_user.id})
						UNION
						SELECT
							t.title as title,
							t.treatment_date as date,
							'-' as professional,
							t.establishment_name as establishment,
							'appointments/' || t.appointment_id || '/treatments/' || t.id as link
						FROM
							treatments t
						WHERE
							t.title ILIKE '%#{params[:search]}%' AND
							t.appointment_id IN (SELECT id
								FROM appointments
								WHERE user_id = #{current_user.id})"

      @results = ActiveRecord::Base.connection.execute(sql)

      respond_to do |format|
        format.js
        return
      end
    end

    @appointments = current_user.appointments.order(appointment_date: :desc).limit(3)
    @exams = current_user.exams.order(exam_date: :desc).limit(3)
    @treatments = current_user.treatments.order(treatment_date: :desc).limit(3)

    respond_to do |format|
      format.html
    end
  end

  # def users_sharing_with_me
  #   @shared_history = current_user.users_sharing_with_me
  #   render 'dashboard/users_sharing_with_me'
  # end
end

app/views/dashboard/_search_results.html.erb
<!-- This partial renders on the dashboard the search data that the user entered about exam, treatments or appointments -->
<% if results.count > 0 %>
<div class="tables_standart">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col" class="align-middle text-center font-weight-bold">Título</th>
        <th scope="col" class="align-middle text-center font-weight-bold">Data</th>
        <th scope="col" class="align-middle text-center font-weight-bold">Nome do Profissional</th>
        <th scope="col" class="align-middle text-center font-weight-bold">Estabelecimento</th>
      </tr>
    </thead>
    <tbody>    
      <% results.each do |result| %>
        <tr>
          <td>
            <%= link_to result['title'], result['link'], class:"text-decoration-none results_tables" %>
          </td>
          <td class="text-decoration-none results_tables">
            <%= result['date'].to_time.strftime('%d/%m/%Y') %>
          </td>
          <td class="text-decoration-none results_tables">
            <%= result['professional'] %>
          </td>
          <td class="text-decoration-none results_tables">
            <%= result['establishment'] %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% else %>
  <h4>Consulta não retornou nenhum registro.</h4>
<% end %>

app/views/dashboard/index.html.erb
<p id="notice">
  <%= notice %>
</p>

<!-- Search from -->
	<%= form_tag dashboard_path, method: :get, remote: true, class:"mb-5" do %>
		<div class="conteiner search_field_dashboard">		
			<%= text_field_tag 'search', @search, class:'search-box' %>	
			<span class="search-button">
				<span class="search-icon"><%= submit_tag "", id:"search_for_consults" %></span>
  		</span>
  	</div>
	<% end %>

	<!-- Search results -->
	<div id="results" class="row ml-3 mr-3 justify-content-sm-center mb-5"></div>
	
	<div class='row ml-3 mr-3 justify-content-sm-center'>
  	<div class='col-xl-4 col-sm-4 col-md-4'>
    	
      <table class="table table-striped">
			  <thead>
			    <tr>
			      <th scope="col" class = "header_tables_dashboard text-center font-weight-bold"><%= link_to 'Consultas', appointments_path, id:"header_table_appointment"  %></th>
					</tr>
				</thead>
				<% if @appointments.present? %>
					<tbody>
						<% @appointments.each do |appointment| %>
							<tr>
								<% @title = "#{appointment.title} #{appointment.appointment_date.strftime('%d/%m')}" %>
								<td class="text-center"><%= link_to "#{@title}", appointment_path(appointment), class:"text-decoration-none results_tables"%></td>
							</tr>
						<% end %>
					</tbody>
				<% end %>
			</table>
		</div>

		<div class='col-xl-4 col-sm-4 col-md-4'>
    	<table class="table table-striped">
			  <thead>
			    <tr>
			      <th scope="col" class = "header_tables_dashboard text-center font-weight-bold"><span id="header_table_appointment">Exames</span></th>
					</tr>
				</thead>
				<% if @exams.present? %>
					<tbody>
						<% @exams.each do |exam| %>
							<tr>
								<% @title = "#{exam.title} #{exam.exam_date.strftime('%d/%m')}" %>
								<td class="text-center"><%= link_to "#{@title}",appointment_exam_path(appointment_id: exam.appointment_id, id: exam.id), class:"text-decoration-none results_tables"%></td>
							</tr>
						<% end %>
					</tbody>
				<% end %>
			</table>
    </div>

		<div class='col-xl-4 col-sm-4 col-md-4'>     	
    	<table class="table table-striped">
			  <thead>
			    <tr>
			      <th scope="col" class = "header_tables_dashboard text-center font-weight-bold"><span id="header_table_appointment">Tratamentos</span></th>
					</tr>
				</thead>
				
				<% if @treatments.present? %>
					<tbody>
						<% @treatments.each do |treatment| %>
							<tr>
								<% @title = "#{treatment.title} #{treatment.treatment_date.strftime('%d/%m')}" %>
								<td class="text-center"><%= link_to "#{@title}",appointment_treatment_path(appointment_id: treatment.appointment_id, id: treatment.id), class:"text-decoration-none results_tables"%></td>
							</tr>
						<% end %>
					</tbody>
				<% end %>
			</table>
  	</div>

	</div>
	

app/views/dashboard/index.js.erb
$("#results").html("<%= j render partial: "search_results", locals: { results: @results } %> ");