config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  resources :appointments do
    resources :exams, except: [:index] do
      member do
        delete :delete_exam_attached
      end
    end
    resources :treatments, except: [:index]
  end

  get 'home', to: 'home#index'

  get '/dashboard', to: 'dashboard#index'
  get '/shared_history', to: 'shared_users#index'
  post '/search_shared_user', to: 'shared_users#search_user'

  resources :shared_users, only: %i[destroy create]

  devise_for :users
  get '/user' => 'dashboard#index', as: :user_root

  ## Essas linha de codigo tem que esta por ultimo.
  get 'fatal_test', to: 'errors#fatal_test'
  get 'error_test', to: 'errors#error_test'

  match '*path', to: 'errors#not_found', via: :all
  ##
end

app/models/appointment.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: appointments
#
#  id                :bigint           not null, primary key
#  title             :string           not null
#  description       :text             not null
#  professional_name :string           not null
#  appointment_date  :date             not null
#  user_id           :bigint           not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
class Appointment < ApplicationRecord
  # Active Record Associations
  belongs_to :user
  has_many :exams, dependent: :destroy
  has_many :treatments, dependent: :destroy

  # Active Record Validations
  validates :title, :description, :professional_name, :appointment_date, presence: true
end

app/controllers/appointments_controller.rb
# frozen_string_literal: true

class AppointmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_user

  before_action :set_appointment, only: %i[show edit update destroy]
  layout 'dashboard'
  # GET /appointments
  def index
    @appointments = get_user.appointments
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show; end

  # GET /appointments/new
  def new
    @appointment = get_user.appointments.build
  end

  # GET /appointments/1/edit
  def edit; end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = get_user.appointments.build(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'A consulta foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'A consulta foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'A consulta foi deletada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private

  # Check relation between current_user and other user

  def get_user
    if user_check_present?
      if sharing_with_me?
        @shared_user = sharing_with_me?.presence
      else
        redirect_to appointments_path, notice: 'Usuário não compartilhado!'
      end
    else
      current_user
    end
  end

  def user_check_present?
    params[:user_check].present?
  end

  def sharing_with_me?
    current_user.users_sharing_with_me.find_by(id: params[:user_check])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_appointment
    @appointment = Appointment.find_by(id: params[:id])
  end

  # Only allow a list of trusted parameters through.
  def appointment_params
    params.require(:appointment).permit(:title, :description, :professional_name, :appointment_date, :user_id)
  end
end

app/helpers/appointments_helper.rb
# frozen_string_literal: true

module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<div class="container">
  <div class="d-flex justify-content-center col-sm-12 col-md-10 col-lg">
    <div class="col-lg-10">
			<%= simple_form_for @appointment, defaults: { input_html: { class: 'form-control' } } do |f| %>
  			<%= f.error_notification %>
  			<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
	
  			<div class="form-group">
  			  <%= f.input :title, label: 'Título' %>
  			  <%= f.input :description, label: 'Descrição' %>
  			  <%= f.input :professional_name, label: 'Profissional' %>
  			  <%= f.datetime_field :appointment_date %>

          <% if action_name == 'edit'%>  
            <%= f.button :submit, "Editar Consulta" , {class:"btn mt-3 button-submit-auth-entry mb-4 btn-lg btn-block text-center"} %>
          <% else %>
            <%= f.button :submit, "Criar Consulta" , {class:"btn mt-3 button-submit-auth-entry mb-4 btn-lg btn-block text-center"} %>
          <% end %>        
        </div>
			<% end %>
		</div>
	</div>
</div>

app/views/appointments/edit.html.erb
<div class="container-fluid show_card tables_standart">
  <div class="cards">
    <div class="card">
    	<div class="contents ">
				<div class="container-sm interactive_button">
					<h1 class="text-center">Editar Consulta</h1>
					<%= render 'form', appointment: @appointment %>
					<%= link_to 'Voltar', @appointment, class:"btn-info button_style_horizontal btn mb-4 text-left" %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/appointments/index.html.erb
<p id="notice">
  <%= notice %>
</p>

<div class="tables_standart mb-5">
  <h1>Consultas</h1>

  <table class="table table-hover" data-toggle="table" data-search="true" data-strict-search="true">
    <thead>
      <tr>
        <th>Titulo</th>
        <th>Nome do Profissional</th>
        <th>Data da Consulta</th>
        <th colspan="3" style="background-color: var(--color-primary)"></th>
      </tr>
    </thead>

    <tbody>
      <% @appointments.each do |appointment| %>
        </tr>
          <td>
            <%= appointment.title %>
          </td>
          <td>
            <%= appointment.professional_name %>
          </td>
          <td>
            <%= appointment.appointment_date.strftime('%d/%m/%y') %>
          </td>
          <td>
            <%= link_to appointment do %>
              <%= image_tag 'icon_show.svg' %>
            <% end %>
          </td>

          <% unless @shared_user%>
            <td>
              <%= link_to edit_appointment_path(appointment) do %>
                <%= image_tag 'icon_edit.svg' %>
              <% end %>
            </td>
            <td>
              <%= link_to appointment, method: :delete, data: { confirm: 'Você tem certeza?' } do %>
                <%= image_tag('icon_trash.svg')%>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% unless @shared_user %>
    <button class="button_shape create_instance btn-lg btn-block interactive_button mt-5">
      <%= link_to 'Nova consulta' , new_appointment_path %>
    </button>
  <% end %>
</div>

app/views/appointments/new.html.erb
<div class="container-fluid show_card tables_standart">
  <div class="cards">
    <div class="card">
    	<div class="contents ">
				<div class="container interactive_button">
					<h1 class="text-center">Nova Consulta</h1>
					<%= render 'form', appointment: @appointment %>
					<%= link_to 'Voltar', appointments_path, class:"btn-info button_style_horizontal btn mb-4 text-left" %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/appointments/show.html.erb
<p id="notice">
  <%= notice %>
</p>
<div class="container-fluid show_card">
  <div class="cards">
    <div class="card">
      <input type="checkbox" id="bgtoggle" class="toggle" />
      <label for="bgtoggle" class="menu"></label>

      <!-- Data the appointments -->

      <div class="contents">
        <div class="container-fluid">
          <div class="row mb-3">
            <h5 class="attribute_camp mr-4">Título da Consulta :</h5> <span class="attribute_value">
              <%= @appointment.title %>
            </span>
          </div>

          <div class="row mb-3">
            <h5 class="attribute_camp mr-4">Nome do Profissional :</h5> <span class="attribute_value">
              <%= @appointment.professional_name %>
            </span>
          </div>

          <div class="row mb-3">
            <h5 class="attribute_camp mr-4">Data de Consulta :</h5> <span class="attribute_value">
              <%= @appointment.appointment_date.strftime('%d/%m/%y') %>
            </span>
          </div>

          <div class="row mb-3 mt-5">
            <% if @appointment.exams.any? %>
              <h5 class="attribute_camp mr-4">Exames associados:</h5>
              <div class="container mb-5 ">
                <% @appointment.exams.each do |exam| %>
                  <div class="row tables_standart_show_views">
                    <%= link_to "#{exam.title}" , [@appointment, exam],
                      class: "btn button_shape create_instance text-dark text-decoration-none  mt-2" %>
                  </div>
                  <% end %>
              </div>
              <% end %>
          </div>

          <div class="row mb-4 border-bottom border-dark"
            style="padding-bottom: 2em; color: var(--gray-inputs-legends) ; ">
            <% if @appointment.treatments.any? %>
              <h5 class="attribute_camp mr-4">Tratamentos associados:</h5>
              <div class="container">
                <% @appointment.treatments.each do |treatment| %>
                  <div class="row tables_standart_show_views">
                    <%= link_to "#{treatment.title}" , [@appointment, treatment],
                      class: "btn button_shape create_instance text-dark text-decoration-none  mt-2" %>
                  </div>
                  <% end %>
              </div>
              <% end %>
          </div>

          <% unless current_user !=@appointment.user %>
            <div class="row mb-5 interactive_button">
              <%= link_to 'Editar' , edit_appointment_path(@appointment), class:"button_style_horizontal btn mb-4 btn-sm
                btn-block text-left" %>

                <%= link_to 'Adicionar Exame' , new_appointment_exam_path(@appointment), class:"button_style_horizontal
                  btn mb-4 btn-lg btn-block text-left"%>

                  <%= link_to 'Adicionar Tratamento' , new_appointment_treatment_path(@appointment),
                    class:"button_style_horizontal btn mb-4 btn-lg btn-block text-left" %>

                    <%= link_to 'Voltar ao Histórico' , appointments_path, class:"btn-info button_style_horizontal btn
                      mb-4 btn-lg btn-block text-left" %>
            </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>