config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  resources :appointments do
    resources :exams, except: [:index] do
      member do
        delete :delete_exam_attached
      end
    end
    resources :treatments, except: [:index]
  end

  get 'home', to: 'home#index'

  get '/dashboard', to: 'dashboard#index'
  get '/shared_history', to: 'shared_users#index'
  post '/search_shared_user', to: 'shared_users#search_user'

  resources :shared_users, only: %i[destroy create]

  devise_for :users
  get '/user' => 'dashboard#index', as: :user_root

  ## Essas linha de codigo tem que esta por ultimo.
  get 'fatal_test', to: 'errors#fatal_test'
  get 'error_test', to: 'errors#error_test'

  match '*path', to: 'errors#not_found', via: :all
  ##
end

app/models/exam.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: exams
#
#  id                 :bigint           not null, primary key
#  title              :string           not null
#  description        :text             not null
#  establishment_name :string           not null
#  exam_date          :date             not null
#  appointment_id     :bigint           not null
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  documents          :json
#
class Exam < ApplicationRecord
  has_many_attached :documents
  # CarrierWave Uploader
  # mount_uploaders :documents, DocumentUploader
  # Active Record Associations
  belongs_to :appointment
  has_one :user, through: :appointment

  # Active Record Validations
  validates :title, :description, :establishment_name, :exam_date, presence: true
end

app/controllers/exams_controller.rb
# frozen_string_literal: true

class ExamsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_appointment
  before_action :set_exam, only: %i[show edit update destroy]
  layout 'dashboard'

  # GET /appintment/:appoint_id/exams
  def index
    @exams = @appointment.exams
  end

  # GET /exams/1
  # GET /exams/1.json
  def show; end

  # GET /exams/new
  def new
    @exam = @appointment.exams.build
  end

  # GET /exams/1/edit
  def edit; end

  # POST /exams
  # POST /exams.json
  def create
    @exam = @appointment.exams.build(exam_params)

    respond_to do |format|
      if @exam.save
        # Ao criar um exame você irá para a tela da consulta
        format.html { redirect_to appointment_path(@appointment), notice: 'Exame criado com sucesso.' }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        # Ao fazer a atualização você voltará para tela de update
        format.html { redirect_to appointment_path(@appointment), notice: 'Exame foi atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to appointment_exams_path(@appointment), notice: 'Exame foi deletado com sucesso!' }
      format.json { head :no_content }
    end
  end

  def delete_exam_attached
    @exam = ActiveStorage::Blob.find_signed(params[:id])
    exam = ActiveStorage::Attachment.find_by(record_type: 'Exam', blob_id: @exam.id)
    exam_id = exam.record_id
    exam.purge
    @exam = Exam.find(exam_id)
    redirect_to appointment_exam_path(@exam.appointment, @exam)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_exam
    @exam = @appointment.exams.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def exam_params
    params.require(:exam).permit(:title, :description, :establishment_name, :exam_date, :appointment_id,
                                 documents: [])
  end

  def get_appointment
    @appointment = Appointment.find(params[:appointment_id])
  end
end

app/helpers/exams_helper.rb
# frozen_string_literal: true

module ExamsHelper
end

app/views/exams/_form.html.erb
<!--
  Mostrar o titulo do exame 
  Mostrar a descriação do exame 
  Mostrar o nome do esbelecimento onde foi feito o exame 
  Mostrar a data do exame 
  Motrar o campo de associação de documentos 
  Tem um botão para criar o exame ou salvar exame 
-->
<div class="container">
  <div class="d-flex justify-content-center col-sm-12 col-md-10 col-lg">
    <div class="col-lg-10">
      <%= simple_form_for([@appointment, @exam]) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
        <div class="form-group">
          <%= f.input :title, label: 'Título' %>
          <%= f.input :description, label: 'Descrição' %>
          <%= f.input :establishment_name %>
          <%= f.datetime_field :exam_date %>
          <%= f.label 'Documentos' %>
          <%= f.file_field :documents, multiple: true %>
          <%= f.button :submit, "Enviar", { class: "btn mt-3 button-submit-auth-entry mb-4 btn-lg
                              btn-block text-center" } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/exams/edit.html.erb
<div class="container-fluid show_card tables_standart">
  <div class="cards">
    <div class="card">
    	<div class="contents ">
				<div class="container-sm interactive_button">
					<h1 class="text-center">Editar Exames</h1>
					<%= render 'form', exam: @exam %>
					<%= link_to 'Voltar', appointment_path(@appointment), class:"btn-info button_style_horizontal btn mb-4 text-left" %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/exams/index.html.erb
<!-- Não há um index no projeto -->

<p id="notice">
  <%= notice %>
</p>

<div class="tables_standart mb-5">
  <h1>Exams</h1>

  <table class="table table-hover" data-toggle="table" data-search="true" data-strict-search="true">

    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Establishment name</th>
        <th>Exam date</th>
        <th>Appointment</th>
        <th colspan="3" style="background-color: var(--color-primary)"></th>
      </tr>
    </thead>

    <tbody>
      <% @exams.each do |exam| %>
        <tr>
          <td>
            <%= exam.title %>
          </td>
          <td>
            <%= exam.description %>
          </td>
          <td>
            <%= exam.establishment_name %>
          </td>
          <td>
            <%= exam.exam_date %>
          </td>
          <td>
            <%= exam.appointment_id %>
          </td>

          <td>
            <%= link_to image_tag('icon_show.svg'), [@appointment] %>
          </td>
          <% unless exam.user !=current_user %>
            <td>
              <%= link_to image_tag('icon_edit.svg'), edit_appointment_exam_path(@appointment, exam) %>
            </td>
            <td>
              <%= link_to image_tag('icon_trash.svg'), [@appointment, exam], method: :delete, data: {
                confirm: 'Are you sure?' } %>
            </td>
            <% end %>

        </tr>
        <% end %>
    </tbody>
  </table>
  <% unless @appointment.user !=current_user %>
    <button class="button_shape create_instance btn-lg btn-block interactive_button mt-5">
      <%= link_to 'New Exam' , new_appointment_exam_path(@appointment) %>
    </button>
    <% end %>
</div>

app/views/exams/new.html.erb
<div class="container-fluid show_card tables_standart">
  <div class="cards">
    <div class="card">
    	<div class="contents ">
				<div class="container-sm interactive_button">
					<h1 class="text-center">Novo Exame</h1>
					<%= render 'form', exam: @exam %>
					<%= link_to 'Back', appointment_path(@appointment), class:"btn-info button_style_horizontal btn mb-4 text-left" %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/exams/show.html.erb
<!--
  Tablela com detalhe de todos os dados rápido do exame Título > Data > Local do Exame
  Botão para editar o exame
  Botão para deletar o exame
-->
<p id="notice">
  <%= notice %>
</p>
<div class="container-fluid show_card">
  <div class="cards">
    <div class="card">
      <input type="checkbox" id="bgtoggle" class="toggle" />
      <label for="bgtoggle" class="menu"></label>

      <!-- Data the exams -->
      <div class="contents">
        <div class="container-fluid">
          <div class="row mb-3">
            <h5 class="attribute_camp mr-4">Título do Tratamento :</h5> <span class="attribute_value">
              <%= @exam.title %>
            </span>
          </div>

          <div class="row mb-3">
            <h5 class="attribute_camp mr-4">Data de Exame :</h5> <span class="attribute_value">
              <%= @exam.exam_date.strftime('%d/%m/%y') %>
            </span>
          </div>

          <div class="row mb-3 border-bottom-2 border-success ">
            <h5 class="attribute_camp mr-4">Local de Exame :</h5> <span class="attribute_value">
              <%= @exam.establishment_name %>
            </span>
          </div>

          <div class="row mb-3">
            <h5 class="attribute_camp mr-4">
              <%= image_tag 'icon_file.svg' , class: "ml-2" %> Documentos :
            </h5>
            <div class="container">
              <% @exam.documents.each do |document| %>
                <div class="row ml-5">
                  <button type="button" class="btn btn-success">
                    <div class="col">
                      <%= link_to "Anexo: #{document.filename.to_s}" , document.service_url, target: '_blank' ,
                        class: "text-decoration-none text-light bold font-weight-bold" %>
                        <%= link_to 'Remove' , delete_exam_attached_appointment_exam_path(@exam.appointment_id,
                          document.signed_id), method: :delete, data: { confirm: 'Tem certeza?' } %>
                    </div>
                  </button>
                </div>
            </div>
            <% end %>
          </div>

          <% unless @exam.user !=current_user %>
            <div class="row mt-5 interactive_button">

              <%= link_to 'Editar' , edit_appointment_exam_path(@appointment, @exam), class:"button_style_horizontal btn
                mb-4 btn-sm btn-block text-left" %>

                <%= link_to 'Remover Exame' , [@appointment, @exam], method: :delete, data: {
                  confirm: 'Você tem certeza?' }, class:"btn button_style_horizontal btn mb-4 btn-sm btn-block
                  text-left" %>

                  <%= link_to 'Voltar à Consulta' , appointment_path(@appointment), class:"btn-info
                    button_style_horizontal btn mb-4 btn-sm btn-block text-left" %>
            </div>
            <% end%>
        </div>
      </div>
    </div>
  </div>
</div>